// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://djoopdqhwniekcifzcok.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRqb29wZHFod25pZWtjaWZ6Y29rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0NDkzNTAsImV4cCI6MjA3NDAyNTM1MH0.ebyPhX_8a6lV89_zQJgUk0QjYGM1ZWQsyH07pXgRcqg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});